development:
  adapter:  postgresql
  database: finesse_development
  host:     localhost
  username: postgres
  password: dobermann

production:
  adapter:  postgresql
  database: finesse_production
  host:     localhost
  username: postgres
  password: dobermann